#!/bin/sh

DNS_SERVER_IP=localhost
MEMCACHED_SERVER_IP=localhost
MEMCACHED_SERVER_PORT=11211
MEMCACHED_EXPIRATION_TIME=86400

function save_hostname_to_cache {
  local IP_ADDR=$1 
  local HOSTNAME=$2   
  local RESULT=`echo -e "set $IP_ADDR 0 $MEMCACHED_EXPIRATION_TIME ${#HOSTNAME}\r\n$HOSTNAME\r" | nc $MEMCACHED_SERVER_IP $MEMCACHED_SERVER_PORT`
  if [[ "$RESULT" == "STORED" ]]; then 
    return 0
  else
    return 1
  fi
}

function get_hostname_from_cache {
  CACHED_HOSTNAME=`echo -e "get $1\r" | nc $MEMCACHED_SERVER_IP $MEMCACHED_SERVER_PORT | sed -e '1d;$d'`
  return 0
}

function send_response {
  echo -e "Content-type: text/plain\n\n$1"
}

IP_ADDR=`echo $QUERY_STRING | awk -F"=" '/ip=/{ print $2 }'`
if [[ -z $IP_ADDR ]]; then
  send_response
  exit 0
fi

HOSTNAME=`nslookup $IP_ADDR $DNS_SERVER_IP | awk '($2 == "name") {print $4}' | sed 's/.lan$//'`

if [[ -z $HOSTNAME ]]; then
  NETBIOS_NAME=`timeout 0.3s nmblookup -A $IP_ADDR | awk '$2 == "<20>" { print $1 }'`
 
  if [[ -z $NETBIOS_NAME ]]; then
    get_hostname_from_cache $IP_ADDR
    HOSTNAME=$CACHED_HOSTNAME
  else  
    HOSTNAME=$NETBIOS_NAME
    save_hostname_to_cache $IP_ADDR $HOSTNAME
  fi
fi

send_response $HOSTNAME
